package com.strikevision.app;

import android.Manifest;import android.content.*;import android.content.pm.*;import android.graphics.*;import android.graphics.drawable.*;import android.media.Image;import android.os.*;import android.view.*;import android.widget.*;import java.util.*;import java.util.concurrent.*;
import androidx.activity.ComponentActivity;import androidx.camera.core.*;import androidx.camera.lifecycle.ProcessCameraProvider;import androidx.camera.view.PreviewView;import androidx.core.content.ContextCompat;import com.google.common.util.concurrent.ListenableFuture;
import com.google.mlkit.vision.common.InputImage;import com.google.mlkit.vision.pose.*;import com.google.mlkit.vision.pose.defaults.PoseDetectorOptions;

public class MainActivity extends ComponentActivity{
 FrameLayout root;PreviewView pv;LinearLayout hud;TextView stat,poseTxt,velTxt,countTxt,recTxt;Handler ui=new Handler(Looper.getMainLooper());ExecutorService ex;PoseDetector det;SharedPreferences sp;int secs=5,frames,poses;boolean active,processing,burst;long end,lastHot,lastT;double vel,peak,scale=120;String peakName="Strike";HashMap<Integer,PointF> last=new HashMap<>();ArrayList<Integer> speeds=new ArrayList<>(),powers=new ArrayList<>();ArrayList<String> log=new ArrayList<>();int[] weapons={PoseLandmark.LEFT_WRIST,PoseLandmark.RIGHT_WRIST,PoseLandmark.LEFT_ANKLE,PoseLandmark.RIGHT_ANKLE};
 public void onCreate(Bundle b){super.onCreate(b);sp=getSharedPreferences("sv_pose",0);ex=Executors.newSingleThreadExecutor();det=PoseDetection.getClient(new PoseDetectorOptions.Builder().setDetectorMode(PoseDetectorOptions.STREAM_MODE).build());if(Build.VERSION.SDK_INT>=23&&checkSelfPermission(Manifest.permission.CAMERA)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.CAMERA},9);else screen();}
 public void onRequestPermissionsResult(int r,String[] p,int[] g){super.onRequestPermissionsResult(r,p,g);screen();}protected void onDestroy(){super.onDestroy();try{det.close();}catch(Throwable t){}try{ex.shutdown();}catch(Throwable t){}}
 void screen(){root=new FrameLayout(this);pv=new PreviewView(this);pv.setScaleType(PreviewView.ScaleType.FILL_CENTER);root.addView(pv,new FrameLayout.LayoutParams(-1,-1));hud=new LinearLayout(this);hud.setOrientation(LinearLayout.VERTICAL);hud.setPadding(26,52,26,32);hud.setBackgroundColor(Color.argb(72,0,0,0));root.addView(hud,new FrameLayout.LayoutParams(-1,-1));setContentView(root);center("STRIKEVISION",30,Color.WHITE);center("Pose Core v1.3 | CameraX + ML Kit",13,Color.rgb(163,255,18));stat=center("Starting pose camera...",16,Color.rgb(163,255,18));poseTxt=center("Frames: 0 | Pose: 0",15,Color.LTGRAY);velTxt=center("Weapon velocity: 0",15,Color.rgb(59,130,246));countTxt=center("Strikes: 0",17,Color.WHITE);recTxt=center("Record impact: "+sp.getInt("rec",0),15,Color.LTGRAY);LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);hud.addView(row);Button a=small("5s"),b=small("10s"),c=small("15s");a.setOnClickListener(v->{secs=5;stat.setText("5 sec selected");});b.setOnClickListener(v->{secs=10;stat.setText("10 sec selected");});c.setOnClickListener(v->{secs=15;stat.setText("15 sec selected");});row.addView(a);row.addView(b);row.addView(c);hud.addView(new View(this),new LinearLayout.LayoutParams(1,0,1));Button start=btn("Start 5-count");start.setOnClickListener(v->begin());hud.addView(start);Button clear=btn("Clear record");clear.setOnClickListener(v->{sp.edit().clear().apply();screen();});hud.addView(clear);loop();camera();}
 void camera(){ListenableFuture<ProcessCameraProvider> f=ProcessCameraProvider.getInstance(this);f.addListener(()->{try{ProcessCameraProvider p=f.get();Preview pr=new Preview.Builder().build();pr.setSurfaceProvider(pv.getSurfaceProvider());ImageAnalysis an=new ImageAnalysis.Builder().setBackpressureStrategy(ImageAnalysis.STRATEGY_KEEP_ONLY_LATEST).build();an.setAnalyzer(ex,this::analyze);p.unbindAll();p.bindToLifecycle(this,CameraSelector.DEFAULT_FRONT_CAMERA,pr,an);stat.setText("Pose live. Keep shoulders, wrists, ankles visible.");}catch(Throwable e){stat.setText("CameraX fail: "+e.getClass().getSimpleName());}},ContextCompat.getMainExecutor(this));}
 @androidx.camera.core.ExperimentalGetImage public void analyze(ImageProxy ip){frames++;if(processing){ip.close();return;}Image im=ip.getImage();if(im==null){ip.close();return;}processing=true;InputImage ii=InputImage.fromMediaImage(im,ip.getImageInfo().getRotationDegrees());det.process(ii).addOnSuccessListener(p->pose(p,System.currentTimeMillis())).addOnCompleteListener(t->{processing=false;ip.close();});}
 void pose(Pose p,long now){poses++;PoseLandmark ls=p.getPoseLandmark(PoseLandmark.LEFT_SHOULDER),rs=p.getPoseLandmark(PoseLandmark.RIGHT_SHOULDER);if(ls!=null&&rs!=null){PointF a=ls.getPosition(),b=rs.getPosition();scale=Math.max(60,dist(a,b));}double best=0;String nm="Strike";if(lastT>0){double dt=Math.max(.033,(now-lastT)/1000.0);for(int k:weapons){PoseLandmark lm=p.getPoseLandmark(k);if(lm==null)continue;PointF cur=lm.getPosition(),old=last.get(k);if(old!=null){double v=(dist(cur,old)/scale)/dt;if(v>best){best=v;nm=name(k);}}}}for(int k:weapons){PoseLandmark lm=p.getPoseLandmark(k);if(lm!=null)last.put(k,lm.getPosition());}lastT=now;vel=best;if(active)strike(best,nm);}
 double dist(PointF a,PointF b){double x=a.x-b.x,y=a.y-b.y;return Math.sqrt(x*x+y*y);}String name(int k){if(k==PoseLandmark.LEFT_WRIST)return "Left punch";if(k==PoseLandmark.RIGHT_WRIST)return "Right punch";if(k==PoseLandmark.LEFT_ANKLE)return "Left kick";if(k==PoseLandmark.RIGHT_ANKLE)return "Right kick";return "Strike";}
 void strike(double v,String nm){long n=System.currentTimeMillis();if(n>end){finishRound();return;}double hot=1.15;if(v>hot){if(!burst){burst=true;peak=v;peakName=nm;}if(v>peak){peak=v;peakName=nm;}lastHot=n;}else if(burst&&n-lastHot>170)addStrike();}
 void addStrike(){int mph=Math.max(3,(int)Math.min(70,peak*7.5));int pow=Math.max(1,(int)Math.min(100,peak*14.0));speeds.add(mph);powers.add(pow);log.add("#"+speeds.size()+" "+peakName+" | "+mph+" mph | "+pow+" impact");burst=false;peak=0;}
 void begin(){log.clear();speeds.clear();powers.clear();last.clear();lastT=0;vel=0;peak=0;burst=false;active=false;stat.setText("5");for(int i=4;i>0;i--){final int x=i;ui.postDelayed(()->stat.setText(""+x),(5-i)*1000);}ui.postDelayed(()->{end=System.currentTimeMillis()+secs*1000L;active=true;stat.setText("GO — pose tracking");},5000);ui.postDelayed(()->finishRound(),5000+secs*1000L+350);}
 void finishRound(){if(!active)return;active=false;if(burst&&peak>0)addStrike();int fast=0,hard=0,sum=0;for(int i=0;i<speeds.size();i++){fast=Math.max(fast,speeds.get(i));hard=Math.max(hard,powers.get(i));sum+=speeds.get(i);}int avg=speeds.isEmpty()?0:sum/speeds.size();if(hard>sp.getInt("rec",0))sp.edit().putInt("rec",hard).putInt("fast",fast).apply();hud.removeAllViews();center("Pose Round Complete",28,Color.WHITE);center(speeds.size()+" strikes",30,Color.rgb(163,255,18));center("Fastest: "+fast+" mph",22,Color.rgb(59,130,246));center("Hardest: "+hard+" impact",22,Color.rgb(59,130,246));center("Average: "+avg+" mph",17,Color.LTGRAY);center("Record impact: "+sp.getInt("rec",0),17,Color.rgb(163,255,18));center("Frames: "+frames+" | Poses: "+poses,13,Color.LTGRAY);String s="";for(String l:log)s+=l+"\n";hud.addView(card("Strike log",s.length()>0?s:"No pose strike detected. Step back until shoulders + wrists are visible, use bright light, then punch across camera."));hud.addView(new View(this),new LinearLayout.LayoutParams(1,0,1));Button again=btn("Run again");again.setOnClickListener(v->screen());hud.addView(again);}
 void loop(){ui.postDelayed(new Runnable(){public void run(){if(poseTxt!=null)poseTxt.setText("Frames: "+frames+" | Poses: "+poses+" | Scale: "+Math.round(scale));if(velTxt!=null)velTxt.setText("Weapon velocity: "+String.format(java.util.Locale.US,"%.2f",vel));if(countTxt!=null)countTxt.setText("Strikes: "+speeds.size());ui.postDelayed(this,250);}},250);}
 TextView center(String s,int z,int col){TextView t=txt(s,z,col,Typeface.BOLD);t.setGravity(Gravity.CENTER);hud.addView(t);return t;}TextView txt(String s,int z,int col,int st){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(col);t.setTypeface(Typeface.DEFAULT,st);t.setPadding(0,6,0,6);return t;}Button btn(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(Color.WHITE);b.setTextSize(16);b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);b.setBackground(bg(Color.rgb(59,130,246)));b.setLayoutParams(new LinearLayout.LayoutParams(-1,120));return b;}Button small(String s){Button b=btn(s);b.setLayoutParams(new LinearLayout.LayoutParams(0,98,1));return b;}View card(String a,String b){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(22,20,22,20);c.setBackground(bg(Color.rgb(23,23,23)));c.addView(txt(a,21,Color.WHITE,Typeface.BOLD));c.addView(txt(b,15,Color.LTGRAY,Typeface.NORMAL));return c;}GradientDrawable bg(int c){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(28);g.setStroke(2,Color.rgb(45,45,45));return g;}
}
