package com.strikevision.app;

import android.Manifest;import android.app.*;import android.os.*;import android.content.*;import android.content.pm.*;import android.graphics.*;import android.graphics.drawable.*;import android.hardware.Camera;import android.view.*;import android.widget.*;import java.util.*;

@SuppressWarnings("deprecation")
public class MainActivity extends Activity implements SurfaceHolder.Callback,Camera.PreviewCallback{
 FrameLayout root;LinearLayout hud;SurfaceView sv;Camera cam;TextView stat,motionTxt,countTxt,recTxt;Handler h=new Handler(Looper.getMainLooper());SharedPreferences sp;byte[] prev;int w,hgt,secs=5,frames;double motion,peak;boolean active,burst;long end,lastHot;ArrayList<Integer> speeds=new ArrayList<>(),powers=new ArrayList<>();
 public void onCreate(Bundle b){super.onCreate(b);sp=getSharedPreferences("sv",0);if(Build.VERSION.SDK_INT>=23&&checkSelfPermission(Manifest.permission.CAMERA)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.CAMERA},1);else ui();}
 public void onRequestPermissionsResult(int r,String[] p,int[] g){super.onRequestPermissionsResult(r,p,g);ui();}protected void onPause(){super.onPause();stop();}
 void ui(){stop();root=new FrameLayout(this);root.setBackgroundColor(Color.BLACK);sv=new SurfaceView(this);sv.getHolder().addCallback(this);root.addView(sv,new FrameLayout.LayoutParams(-1,-1));hud=new LinearLayout(this);hud.setOrientation(LinearLayout.VERTICAL);hud.setPadding(28,55,28,34);hud.setBackgroundColor(Color.argb(78,0,0,0));root.addView(hud,new FrameLayout.LayoutParams(-1,-1));setContentView(root);center("STRIKEVISION",30,Color.WHITE);center("Round Tracker v1.1",13,Color.rgb(163,255,18));stat=center("Pick 5 / 10 / 15 sec",17,Color.rgb(163,255,18));motionTxt=center("Motion: 0",16,Color.rgb(59,130,246));countTxt=center("Strikes: 0",16,Color.WHITE);recTxt=center("Record impact: "+sp.getInt("rec",0),15,Color.LTGRAY);LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);hud.addView(row);Button a=small("5"),b=small("10"),c=small("15");a.setOnClickListener(v->{secs=5;stat.setText("5 sec selected");});b.setOnClickListener(v->{secs=10;stat.setText("10 sec selected");});c.setOnClickListener(v->{secs=15;stat.setText("15 sec selected");});row.addView(a);row.addView(b);row.addView(c);hud.addView(new View(this),new LinearLayout.LayoutParams(1,0,1));Button start=btn("Start 5-count");start.setOnClickListener(v->begin());hud.addView(start);Button clear=btn("Clear record");clear.setOnClickListener(v->{sp.edit().clear().apply();ui();});hud.addView(clear);loop();}
 public void surfaceCreated(SurfaceHolder sh){try{int id=front();if(id<0)id=0;cam=Camera.open(id);Camera.Parameters p=cam.getParameters();Camera.Size s=pick(p.getSupportedPreviewSizes());if(s!=null){w=s.width;hgt=s.height;p.setPreviewSize(w,hgt);cam.setParameters(p);}cam.setDisplayOrientation(90);cam.setPreviewDisplay(sh);cam.setPreviewCallback(this);cam.startPreview();stat.setText("Camera live. Choose round.");}catch(Throwable e){stat.setText("Camera fail: "+e.getClass().getSimpleName());}}
 public void surfaceChanged(SurfaceHolder s,int f,int ww,int hh){}public void surfaceDestroyed(SurfaceHolder s){stop();}
 int front(){try{Camera.CameraInfo i=new Camera.CameraInfo();for(int n=0;n<Camera.getNumberOfCameras();n++){Camera.getCameraInfo(n,i);if(i.facing==Camera.CameraInfo.CAMERA_FACING_FRONT)return n;}}catch(Throwable t){}return-1;}Camera.Size pick(List<Camera.Size> xs){if(xs==null||xs.isEmpty())return null;Camera.Size best=xs.get(0);for(Camera.Size s:xs){int px=s.width*s.height;if(px>250000&&px<1000000)return s;if(px<best.width*best.height)best=s;}return best;}void stop(){try{if(cam!=null){cam.setPreviewCallback(null);cam.stopPreview();cam.release();}}catch(Throwable t){}cam=null;}
 public void onPreviewFrame(byte[] data,Camera c){frames++;if(w<1||hgt<1||data==null)return;int sw=32,sh=24;byte[] now=new byte[sw*sh];int k=0;for(int y=0;y<sh;y++){int row=(y*hgt/sh)*w;for(int x=0;x<sw;x++)now[k++]=data[row+x*w/sw];}if(prev!=null){long d=0;for(int i=0;i<now.length;i++)d+=Math.abs((now[i]&255)-(prev[i]&255));motion=d/(double)now.length;if(active)strike(motion);}prev=now;}
 void strike(double m){long n=System.currentTimeMillis();if(n>end){finish();return;}if(m>10){peak=Math.max(peak,m);burst=true;lastHot=n;}else if(burst&&n-lastHot>180){int mph=Math.max(3,(int)Math.min(50,peak*.55));int pow=Math.max(1,(int)Math.min(100,peak*1.25));speeds.add(mph);powers.add(pow);peak=0;burst=false;}}
 void begin(){prev=null;frames=0;motion=0;peak=0;active=false;burst=false;speeds.clear();powers.clear();stat.setText("5");for(int i=4;i>0;i--){final int x=i;h.postDelayed(()->stat.setText(""+x),(5-i)*1000);}h.postDelayed(()->{end=System.currentTimeMillis()+secs*1000L;active=true;stat.setText("GO");},5000);h.postDelayed(()->finish(),5000+secs*1000L+300);}
 void finish(){if(!active)return;active=false;if(burst&&peak>0)strike(0);int fast=0,hard=0,sum=0;for(int i=0;i<speeds.size();i++){fast=Math.max(fast,speeds.get(i));hard=Math.max(hard,powers.get(i));sum+=speeds.get(i);}int avg=speeds.isEmpty()?0:sum/speeds.size();if(hard>sp.getInt("rec",0))sp.edit().putInt("rec",hard).putInt("fast",fast).apply();hud.removeAllViews();center("Round Complete",30,Color.WHITE);center(speeds.size()+" strikes",30,Color.rgb(163,255,18));center("Fastest: "+fast+" mph",22,Color.rgb(59,130,246));center("Hardest: "+hard+" impact",22,Color.rgb(59,130,246));center("Average: "+avg+" mph",17,Color.LTGRAY);center("Record impact: "+sp.getInt("rec",0),17,Color.rgb(163,255,18));String log="";for(int i=0;i<speeds.size();i++)log+="#"+(i+1)+" "+speeds.get(i)+" mph | "+powers.get(i)+" impact\n";hud.addView(card("Strike log",log.length()>0?log:"No clean strike bursts detected."));hud.addView(new View(this),new LinearLayout.LayoutParams(1,0,1));Button again=btn("Run again");again.setOnClickListener(v->ui());hud.addView(again);}
 void loop(){h.postDelayed(new Runnable(){public void run(){if(motionTxt!=null)motionTxt.setText("Motion: "+Math.round(motion));if(countTxt!=null)countTxt.setText("Strikes: "+speeds.size());h.postDelayed(this,250);}},250);}TextView center(String s,int z,int col){TextView t=txt(s,z,col,Typeface.BOLD);t.setGravity(Gravity.CENTER);hud.addView(t);return t;}TextView txt(String s,int z,int col,int st){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(col);t.setTypeface(Typeface.DEFAULT,st);t.setPadding(0,7,0,7);return t;}Button btn(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(Color.WHITE);b.setTextSize(16);b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);b.setBackground(bg(Color.rgb(59,130,246)));b.setLayoutParams(new LinearLayout.LayoutParams(-1,125));return b;}Button small(String s){Button b=btn(s);b.setLayoutParams(new LinearLayout.LayoutParams(0,105,1));return b;}View card(String a,String b){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(24,22,24,22);c.setBackground(bg(Color.rgb(23,23,23)));c.addView(txt(a,21,Color.WHITE,Typeface.BOLD));c.addView(txt(b,15,Color.LTGRAY,Typeface.NORMAL));return c;}GradientDrawable bg(int c){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(28);g.setStroke(2,Color.rgb(45,45,45));return g;}
}
