package com.strikevision.app;

import android.Manifest;import android.app.*;import android.os.*;import android.content.*;import android.content.pm.*;import android.graphics.*;import android.graphics.drawable.*;import android.hardware.Camera;import android.view.*;import android.widget.*;import java.util.*;

@SuppressWarnings("deprecation")
public class MainActivity extends Activity implements SurfaceHolder.Callback,Camera.PreviewCallback{
 FrameLayout root;LinearLayout hud;SurfaceView sv;Camera cam;TextView stat,motionTxt,countTxt,recTxt,frameTxt;Handler hh=new Handler(Looper.getMainLooper());SharedPreferences sp;byte[] prev;int w,hgt,secs=5,frames,sens=2;double motion,avgMotion,peak,base=2.0,hot=6.0;boolean active,burst;long end,lastHot;ArrayList<Integer> speeds=new ArrayList<>(),powers=new ArrayList<>();
 public void onCreate(Bundle b){super.onCreate(b);sp=getSharedPreferences("sv",0);if(Build.VERSION.SDK_INT>=23&&checkSelfPermission(Manifest.permission.CAMERA)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.CAMERA},1);else ui();}
 public void onRequestPermissionsResult(int r,String[] p,int[] g){super.onRequestPermissionsResult(r,p,g);ui();}protected void onPause(){super.onPause();stop();}
 void ui(){stop();root=new FrameLayout(this);root.setBackgroundColor(Color.BLACK);sv=new SurfaceView(this);sv.getHolder().addCallback(this);root.addView(sv,new FrameLayout.LayoutParams(-1,-1));hud=new LinearLayout(this);hud.setOrientation(LinearLayout.VERTICAL);hud.setPadding(26,52,26,32);hud.setBackgroundColor(Color.argb(72,0,0,0));root.addView(hud,new FrameLayout.LayoutParams(-1,-1));setContentView(root);center("STRIKEVISION",30,Color.WHITE);center("Weapon Burst v1.2 | adaptive detector",13,Color.rgb(163,255,18));stat=center("Pick time + sensitivity",17,Color.rgb(163,255,18));motionTxt=center("Burst: 0 | Avg: 0 | Hot: 6",14,Color.rgb(59,130,246));frameTxt=center("Frames: 0",14,Color.LTGRAY);countTxt=center("Strikes: 0",16,Color.WHITE);recTxt=center("Record impact: "+sp.getInt("rec",0),15,Color.LTGRAY);LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);hud.addView(row);Button a=small("5s"),b=small("10s"),c=small("15s");a.setOnClickListener(v->{secs=5;stat.setText("5 sec selected");});b.setOnClickListener(v->{secs=10;stat.setText("10 sec selected");});c.setOnClickListener(v->{secs=15;stat.setText("15 sec selected");});row.addView(a);row.addView(b);row.addView(c);LinearLayout row2=new LinearLayout(this);row2.setOrientation(LinearLayout.HORIZONTAL);hud.addView(row2);Button lo=small("Low"),me=small("Med"),hi=small("High");lo.setOnClickListener(v->{sens=1;stat.setText("Low sensitivity");});me.setOnClickListener(v->{sens=2;stat.setText("Medium sensitivity");});hi.setOnClickListener(v->{sens=3;stat.setText("High sensitivity");});row2.addView(lo);row2.addView(me);row2.addView(hi);hud.addView(new View(this),new LinearLayout.LayoutParams(1,0,1));Button start=btn("Start 5-count");start.setOnClickListener(v->begin());hud.addView(start);Button clear=btn("Clear record");clear.setOnClickListener(v->{sp.edit().clear().apply();ui();});hud.addView(clear);loop();}
 public void surfaceCreated(SurfaceHolder sh){try{int id=front();if(id<0)id=0;cam=Camera.open(id);Camera.Parameters p=cam.getParameters();Camera.Size s=pick(p.getSupportedPreviewSizes());if(s!=null){w=s.width;hgt=s.height;p.setPreviewSize(w,hgt);cam.setParameters(p);}try{p.setFocusMode(Camera.Parameters.FOCUS_MODE_CONTINUOUS_VIDEO);cam.setParameters(p);}catch(Throwable x){}cam.setDisplayOrientation(90);cam.setPreviewDisplay(sh);cam.setPreviewCallback(this);cam.startPreview();stat.setText("Camera live. Watch Burst meter.");}catch(Throwable e){stat.setText("Camera fail: "+e.getClass().getSimpleName());}}
 public void surfaceChanged(SurfaceHolder s,int f,int ww,int hh){}public void surfaceDestroyed(SurfaceHolder s){stop();}
 int front(){try{Camera.CameraInfo i=new Camera.CameraInfo();for(int n=0;n<Camera.getNumberOfCameras();n++){Camera.getCameraInfo(n,i);if(i.facing==Camera.CameraInfo.CAMERA_FACING_FRONT)return n;}}catch(Throwable t){}return-1;}Camera.Size pick(List<Camera.Size> xs){if(xs==null||xs.isEmpty())return null;Camera.Size best=xs.get(0);for(Camera.Size s:xs){int px=s.width*s.height;if(px>250000&&px<1000000)return s;if(px<best.width*best.height)best=s;}return best;}void stop(){try{if(cam!=null){cam.setPreviewCallback(null);cam.stopPreview();cam.release();}}catch(Throwable t){}cam=null;}
 public void onPreviewFrame(byte[] data,Camera c){frames++;if(w<1||hgt<1||data==null)return;int sw=40,sh=30;byte[] now=new byte[sw*sh];int k=0;for(int y=0;y<sh;y++){int row=(y*hgt/sh)*w;for(int x=0;x<sw;x++)now[k++]=data[row+x*w/sw];}if(prev!=null){int[] dif=new int[now.length];long sum=0;for(int i=0;i<now.length;i++){int d=Math.abs((now[i]&255)-(prev[i]&255));dif[i]=d;sum+=d;}Arrays.sort(dif);int topN=40;long top=0;for(int i=dif.length-topN;i<dif.length;i++)top+=dif[i];avgMotion=sum/(double)now.length;double local=top/(double)topN;motion=Math.max(avgMotion*2.0,local);if(!active&&!burst)base=base*.96+avgMotion*.04;if(active)strike(motion);}prev=now;}
 void strike(double m){long n=System.currentTimeMillis();if(n>end){finishRound();return;}double mult=sens==3?1.15:(sens==2?1.55:2.1);hot=Math.max(2.2,base*mult+1.0);if(m>hot){peak=Math.max(peak,m);burst=true;lastHot=n;}else if(burst&&n-lastHot>140){addStrike();}}
 void addStrike(){int mph=Math.max(3,(int)Math.min(60,peak*.75));int pow=Math.max(1,(int)Math.min(100,peak*1.65));speeds.add(mph);powers.add(pow);peak=0;burst=false;}
 void begin(){prev=null;frames=0;motion=0;avgMotion=0;peak=0;base=2;active=false;burst=false;speeds.clear();powers.clear();stat.setText("5");for(int i=4;i>0;i--){final int x=i;hh.postDelayed(()->stat.setText(""+x),(5-i)*1000);}hh.postDelayed(()->{end=System.currentTimeMillis()+secs*1000L;active=true;stat.setText("GO — throw visible strikes");},5000);hh.postDelayed(()->finishRound(),5000+secs*1000L+350);}
 void finishRound(){if(!active)return;active=false;if(burst&&peak>0)addStrike();int fast=0,hard=0,sum=0;for(int i=0;i<speeds.size();i++){fast=Math.max(fast,speeds.get(i));hard=Math.max(hard,powers.get(i));sum+=speeds.get(i);}int avg=speeds.isEmpty()?0:sum/speeds.size();if(hard>sp.getInt("rec",0))sp.edit().putInt("rec",hard).putInt("fast",fast).apply();hud.removeAllViews();center("Round Complete",30,Color.WHITE);center(speeds.size()+" strikes",30,Color.rgb(163,255,18));center("Fastest: "+fast+" mph",22,Color.rgb(59,130,246));center("Hardest: "+hard+" impact",22,Color.rgb(59,130,246));center("Average: "+avg+" mph",17,Color.LTGRAY);center("Record impact: "+sp.getInt("rec",0),17,Color.rgb(163,255,18));center("Frames: "+frames+" | Last burst: "+Math.round(motion)+" | Hot: "+Math.round(hot),13,Color.LTGRAY);String log="";for(int i=0;i<speeds.size();i++)log+="#"+(i+1)+" "+speeds.get(i)+" mph | "+powers.get(i)+" impact\n";hud.addView(card("Strike log",log.length()>0?log:"No clean weapon bursts detected. Try High sensitivity, brighter light, and keep fists/feet in frame."));hud.addView(new View(this),new LinearLayout.LayoutParams(1,0,1));Button again=btn("Run again");again.setOnClickListener(v->ui());hud.addView(again);}
 void loop(){hh.postDelayed(new Runnable(){public void run(){if(motionTxt!=null)motionTxt.setText("Burst: "+Math.round(motion)+" | Avg: "+Math.round(avgMotion)+" | Hot: "+Math.round(hot));if(frameTxt!=null)frameTxt.setText("Frames: "+frames);if(countTxt!=null)countTxt.setText("Strikes: "+speeds.size());hh.postDelayed(this,250);}},250);}TextView center(String s,int z,int col){TextView t=txt(s,z,col,Typeface.BOLD);t.setGravity(Gravity.CENTER);hud.addView(t);return t;}TextView txt(String s,int z,int col,int st){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(col);t.setTypeface(Typeface.DEFAULT,st);t.setPadding(0,6,0,6);return t;}Button btn(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(Color.WHITE);b.setTextSize(16);b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);b.setBackground(bg(Color.rgb(59,130,246)));b.setLayoutParams(new LinearLayout.LayoutParams(-1,120));return b;}Button small(String s){Button b=btn(s);b.setLayoutParams(new LinearLayout.LayoutParams(0,98,1));return b;}View card(String a,String b){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(22,20,22,20);c.setBackground(bg(Color.rgb(23,23,23)));c.addView(txt(a,21,Color.WHITE,Typeface.BOLD));c.addView(txt(b,15,Color.LTGRAY,Typeface.NORMAL));return c;}GradientDrawable bg(int c){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(28);g.setStroke(2,Color.rgb(45,45,45));return g;}
}
