plugins {
    id 'com.android.application'
}

android {
    namespace 'com.strikevision.app'
    compileSdk 36

    defaultConfig {
        applicationId 'com.strikevision.v2'
        minSdk 23
        targetSdk 35
        versionCode 8
        versionName '4.0-alpha1-omega'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.activity:activity:1.10.1'
    implementation 'androidx.camera:camera-core:1.6.2'
    implementation 'androidx.camera:camera-camera2:1.6.2'
    implementation 'androidx.camera:camera-lifecycle:1.6.2'
    implementation 'androidx.camera:camera-view:1.6.2'
    implementation 'androidx.camera:camera-video:1.6.2'
    implementation 'com.google.mlkit:pose-detection:18.0.0-beta5'
}
